server:
  servlet:
    context-path: /email-service/v${application.version}
spring:
  application:
    name: bloggios-email-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=mail-service
    hikari:
      username: ${POSTGRES_USERNAME} #Postgres Database username
      password: ${POSTGRES_PASSWORD} #Postgres Database password
      maximum-pool-size: ${POSTGRES_POOL_SIZE:100}
      minimum-idle: ${POSTGRES_IDLE:7}
      leak-detection-threshold: 120000
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update # To automatically create and update tables
application:
  version: @version@
  api-key: ${BLOGGIOS_MAIL_API_KEY}
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    allow-redirects: true
    service-url:
      defaultZone: ${EUREKA_URL}
    enabled: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
mail-configuration:
  google-mail: # Please add your gmail details below
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
bg-thread-pool:
  internal-thread:
    thread-prefix: notification-internal-
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 60